### ISSUE TITLE
Moleculenet module renaming

### ISSUE THREAD

**Issue by rbharath** [deepchem/moleculenet#6]
I'm working in a PR on moving some deepchem code over (the parent DeepChem PR won't be merged in until after DeepChem 2.4 release).

As I'm going through the code, I think we have an opportunity to rethink some old DeepChem design descisions. In particular, I propose we rename some module as follows:

- `deepchem.feat` -> `moleculenet.featurizers`
- `deepchem.splits` -> `moleculenet.splitters`
- `deepchem.trans` -> `moleculenet.transformers`

The original names were chosen to be short for ease of import, but with time I think this earlier decision was a mistake. It means that newcomers have to learn new shortened words rather than the natural module name.

What do folks think? CC @peastman @VIGS25 @lilleswing @miaecle

**Comment by peastman** [comment]
That makes sense.

**Comment by rbharath** [comment]
Closing this PR since we're no longer planning to move large amounts of code into this repo.
